export const categories = [
    "Arrays",
    "Strings",
    "Hashing",
    "Two Pointers",
    "Sliding Window",
    "Stack",
    "Queue",
    "Linked List",
    "Recursion",
    "Backtracking",
    "Binary Search",
    "Sorting",
    "Greedy",
    "Dynamic Programming",
    "Bit Manipulation",
    "Math",
    "Number Theory",
    "Matrix",
    "Prefix Sum",
    "Divide and Conquer",
    "Tree",
    "Binary Tree",
    "Binary Search Tree",
    "Trie",
    "Heap / Priority Queue",
    "Graph",
    "BFS",
    "DFS",
    "Topological Sort",
    "Shortest Path",
    "Minimum Spanning Tree",
    "Disjoint Set Union",
    "Segment Tree",
    "Fenwick Tree",
    "Interval Problems",
    "Monotonic Stack",
    "Monotonic Queue",
    "Game Theory",
    "Combinatorics",
    "Geometry",
    "Simulation",
    "Design",
    "Concurrency",
    "Advanced Data Structures"
]